apiVersion: v1
kind: Pod
metadata:
    name: testpod
spec:
    containers:
      - name: testctr
        image: alpine:3.18.2
        command: ["tail", "-f", "/dev/null"]
        resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
            requests:
              cpu: "10m"
              memory: "20Mi"

